### ISSUE TITLE
Option for processing markdown in YAML? 

### ISSUE THREAD

**Issue by JonathanReeve** [tests-always-included/metalsmith-data-loader#3]
I have YAML data that contains markdown. It'd be great if there were an option to process YAML data as markdown. At the moment rendering markdown in YAML is pretty difficult, if not impossible.

**Comment by fidian** [comment]
I do not believe that this would be a good thing to add to my plugin because one should clearly define a scope for a plugin and mine is to merely load data, not convert data. Other users may have data that's reStructuredText or HTML and they may want to extract links or pull out keywords instead.

It does sound like a wonderful idea for a new module. I've replied to your message in the Slack channel.  If you continue to pursue this line of thought, I think others would want it as well, judging from the feedback there.  You may want to process the `files` object and iterate over the properties specified by the plugin's config, maybe like this:

    use(yourPluginName({
        convertProperties: [
            keywords,
            summary,
            title
        ],
        conversionType: "markdown"
    }));

The above is only a suggestion designed to inspire your creative engine.

I'm closing this request because it is beyond the scope of this plugin, but I hope you do not take it like a dismissal of the idea entirely. Please do continue to develop a plugin that meets your needs and possibly is extended to meet the needs of the other users of Metalsmith!
