### ISSUE TITLE
Unable to load JSON files outside of `source()` folder with `directory` option

### ISSUE THREAD

**Issue by jdsteinbach** [tests-always-included/metalsmith-data-loader#9]
In my build, I've got 4 directories in root:
```
/models      // stores json files of data
/public      // destination directory
/src         // source directory
/templates   // hbs layout files
```

I'm trying to tell this plugin to look in that `/models/` for the json files in `metalsmith.js`:
```js
Metalsmith.use(dataLoader({
  directory: 'models/'
}))
```
but I can't seem to get the right value for `directory` to accomplish that. I also tried `/models`, `./models`, & `../models`.

If I use the backtracking path in my front matter I can get there successfully:
```
---
data:
  team: ../models/team.json
  services: ../models/services.json
---
```

But I'd rather be DRY-er in my front matter & just write:
```
---
data:
  team: team.json
  services: services.json
---
```

Is there a way I can reference the `/models/` directory outside of `/src/`?

**Comment by fidian** [comment]
Yes. I am looking at this bug and I'm wondering how I can improve the documentation, so please help me out and let me know where it is bad and could be improved.

First, I have the examples in the `README.md` that list how to get files from the models folder. They are the last two examples in this section: https://github.com/tests-always-included/metalsmith-data-loader#resolving-files

Secondly, I have a working example that pulls data from a models folder. It was linked as "example repository" and it's on GitHub: https://github.com/tests-always-included/metalsmith-data-loader-example

So the answer you're seeking is this. You have to use quotes for the exclamation point to be parsed as a string in some YAML parsers, so that's why I've quoted these particular values.

    ---
    data:
        team: "!team.json"
        services: "!services.json"
    ---

Please reread those sections and let me know what could be done to improve them.

**Comment by jdsteinbach** [comment]
Thanks, @fidian - initially, I didn't pick up that the quotes were required for the models folder use. I can't get to the examples repo now (GH is 404ing your links above) but my recommendation for the that part of the docs would be to add a sentence to that `/models/` example, along the lines of:

> Note: In this example, the `data` file names are enclosed in quotation marks. That's not a required pattern for json files in `/src/` but it is required to reach files outside of `/src/`.

**Comment by fidian** [comment]
Sorry, the right link to the example is here: https://github.com/fidian/metalsmith-data-loader-example

Quotes are only required because the `!` is the first character. That's also dependent on the YAML parser used, but having quotes worked for me and it failed without the quotes.

Thanks for the additional wording. I'll go put that in the README right away.

**Comment by fidian** [comment]
I've updated the README and made a note about it. I took a different direction than your wording. Would the new note and the example in the README have steered you the correct direction?

**Comment by jdsteinbach** [comment]
This is 💯
```
Note: When the metadata path starts with an exclamation point (!), you must use quotes in your YAML frontmatter. Here's a sample.
```

**Comment by fidian** [comment]
Thanks for proofing it for me. I appreciate the feedback you gave me in the last couple days.
